### ISSUE TITLE
Keyword This bug

### ISSUE THREAD

**Issue by pedrotst** [hephaestus-pl/hffj#4]
The following program is not currently accepeted by the parser (from page 399 of the paper)
class A extends Object {
A () {
super () ;
}
}
class B extends Object {
B () {
super () ;
}
}
class Pair extends Object {
A fst ;
B snd ;
Pair (A fst, B snd){
super () ;
this . fst = fst ;
this . snd = snd ;
}**
Pair setfst (A newfst){
return new Pair (newfst, this.snd);**
}
}
new teste ()

**Comment by daniangelos** [comment]
Bug fixed.
