### ISSUE TITLE
TestAbj does not parse field nor fargs type

### ISSUE THREAD

**Issue by pedrotst** [hephaestus-pl/hffj#6]
Parser is not considering the Id of fields or formal arguments. 
Example:

```

class Pair extends Object {
  A fst ;
  B snd ;
  Pair (A fst, B snd){
    super () ;
    this . fst = fst ;
    this . snd = snd ;
}
  Pair setfst (A newfst){
    return new Pair (newfst, this.snd);
  }
}
new teste ()


```

Produces the following tree

CDecl (Id "Pair") ClassObject [FDecl **ClassObject** (Id "fst"),FDecl **ClassObject** (Id "snd")](KDecl %28Id) [Field **ClassObject** (Id "fst"),Field **ClassObject** (Id "snd")] [] [Assignment (Id "fst") (Id "fst"),Assignment (Id "snd") (Id "snd")]) [MethodDecl (ClassId (Id "Pair")) (Id "setfst") [FormalArg ClassObject (Id "newfst"),FormalArg **ClassObject** (Id "newsnd")](TermExp %28NewExp %28Id) [TermVar (Id "newfst"),TermVar (Id "newsnd")]))]

**Comment by pedrotst** [comment]
any ideas why that might happen @rbonifacio ?

**Comment by daniangelos** [comment]
Bug fixed.
